### ISSUE TITLE
Polycom/Poly support?

### ISSUE THREAD

**Issue by trantor** [nethesis/falconieri#1]
Any plan on that front? It is a pretty major voip phone manifacturer.

Cheers.

**Comment by DavidePrincipi** [comment]
Maybe it is out of @andrea-marchionni's radar. However I guess @Amygos is happy to see a pull request. 

What do you think guys?

@trantor can you provide a link to Polycom cloud API documentation?

**Comment by qualidafial** [comment]
[Poly Zero Touch Provisioner API](https://support.polycom.com/content/dam/polycom-support/products/voice/zero-touch-provisioning/user/en/polycom-ztp-api-developer-guide.pdf)

**Comment by nephimitchell** [comment]
I'm currently working on rough draft for Poly (formerly Polycom) support through their ZTP (Zero Touch Provisioning) API. What is the best way to submit this as I don't have permissions?

**Comment by DavidePrincipi** [comment]
Hi @nephimitchell, I think @Amygos is happy to receive a pull request. Just fork this repository, add the changes to your fork then open a pull request to share the changes.

**Comment by Amygos** [comment]
Hi @nephimitchell, if this is your first contribution to a project on Github, you can follow some guides like this one: https://guides.github.com/activities/forking/
